#!/bin/bash

##anchor reference index

echo
while [ -n "$1" ]
do
    case "$1" in
        -i) input="$2"
            input1="-i "
	    input1+=$input
	    shift;;
	-l) left="$2"
            left1="-l "
	    left1+=$left
            shift;;
	-r) right="$2"
            right1="-r " 
	    right1+=$right
            shift;;
	-s) SAF="$2"
            SAF1="-s " 
	    SAF1+=$SAF
            shift;;
        -h) help="$1"
            shift;; 
    esac
    shift
done

if test $help
then
    echo "Python command: AASRA-index.py $help"
    AASRA-index.py $help
else
    echo "Python command: AASRA-index.py $help $input1 $left1 $right1 $SAF1"
    AASRA-index.py $help $input1 $left1 $right1 $SAF1
##build bowtie2 index
    echo "Start building bowtie2 index"
    echo "Bowtie2 command: bowtie2-build -q -f anchored_$input, anchored_$input"
    bowtie2-build -q -f anchored_$input, anchored_$input
fi
